title: Sara Maria Greene
description: Sara Maria Greene is a writer of fiction
repository: dgreene1/saramariagreene
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
url: https://saramariagreene.com/
baseurl: ""
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
logo: /assets/img/SaraSmirkingInGarden.JPG
twitterIcon: /assets/img/twitter-icon-32-by-32.png
showFooter: false
github: [metadata]
include: [CNAME]
