title: Sara Maria Greene
description: Sara Maria Greene is a writer of fiction
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
logo: /assets/img/SaraSmirkingInGarden.JPG
showFooter: false
github: [metadata]
