name: Testing the GitHub Pages publication

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

      # Use ruby/setup-ruby to shorten build times
      # https://github.com/ruby/setup-ruby
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Bundle and serve
      run: |
        bundle exec jekyll serve
