name: Testing the GitHub Pages publication

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: "16"

jobs:
  test-before-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        # Use ruby/setup-ruby to shorten build times
        # https://github.com/ruby/setup-ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci --include=dev

      - name: Install Ruby Dependencies
        run: |
          npm run install:ruby

      - name: Build Jekyll
        run: npm run build

      - name: ensure Cypress tests pass type checking
        run: npm run type-check:cypress

      - name: Start and Run Cypress Test
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: "http://localhost:8080"
          record: true
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
